CREATE TABLE IF NOT EXISTS rpt_customer_period_activity (
  period_start_date DATE NOT NULL COMMENT '分析开始日期',
  period_end_date DATE NOT NULL COMMENT '分析结束日期',
  shop_id VARCHAR(64) NOT NULL COMMENT '店铺/许可证号',
  cust_id VARCHAR(64) NULL COMMENT '客户编码',
  license_code VARCHAR(64) NULL COMMENT '许可证号',
  shop_name VARCHAR(255) NULL COMMENT '店铺名称',
  cust_name VARCHAR(255) NULL COMMENT '客户名称',
  cust_seg_name VARCHAR(64) NULL COMMENT '档位',
  base_type_name VARCHAR(128) NULL COMMENT '业态',
  work_port_name VARCHAR(64) NULL COMMENT '城乡/经营位置',
  sale_dept VARCHAR(128) NULL COMMENT '营销部/区县单位',
  ss_name VARCHAR(128) NULL COMMENT '基层服务站',
  slsman VARCHAR(128) NULL COMMENT '客户经理',
  longitude DECIMAL(12,8) NULL COMMENT '经度',
  latitude DECIMAL(12,8) NULL COMMENT '纬度',
  days_with_data INT NOT NULL DEFAULT 0 COMMENT '有数据天数',
  active_days INT NOT NULL DEFAULT 0 COMMENT '有销售天数',
  active_rate DECIMAL(18,6) NULL COMMENT '动销率=有销售天数/有数据天数',
  period_sale_qty DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期间销售量，SUM(t_big_saleamt)',
  period_purchase_qty DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期间购进量，SUM(t_big_stockamt)',
  period_sale_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期间销售金额，SUM(t_salemny)',
  period_stock_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期间库存金额，SUM(t_stomny)，仅辅助参考',
  end_biz_date DATE NULL COMMENT '期末库存快照日期',
  end_stock_qty DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期末库存量，取期末日 t_big_stoamt',
  end_stock_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期末库存金额，取期末日 t_stomny',
  stock_sale_ratio DECIMAL(18,6) NULL COMMENT '存销比=期末库存量/期间销售量',
  avg_daily_sale_qty DECIMAL(18,6) NULL COMMENT '日均销售量=期间销售量/有数据天数',
  stock_cover_days DECIMAL(18,6) NULL COMMENT '库存可销天数=期末库存量/日均销售量',
  purchase_sale_ratio DECIMAL(18,6) NULL COMMENT '购销比=期间购进量/期间销售量',
  etl_loaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '报表生成时间',
  PRIMARY KEY (period_start_date, period_end_date, shop_id),
  KEY idx_rpt_activity_seg (period_end_date, cust_seg_name, stock_sale_ratio),
  KEY idx_rpt_activity_station (period_end_date, ss_name, slsman),
  KEY idx_rpt_activity_geo (longitude, latitude),
  KEY idx_rpt_activity_stock (period_end_date, end_stock_qty),
  KEY idx_rpt_activity_sale (period_end_date, period_sale_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户期间动销分析宽表';

CREATE TABLE IF NOT EXISTS rpt_cust_seg_period_activity (
  period_start_date DATE NOT NULL COMMENT '分析开始日期',
  period_end_date DATE NOT NULL COMMENT '分析结束日期',
  cust_seg_name VARCHAR(64) NOT NULL COMMENT '档位',
  customer_count INT NOT NULL DEFAULT 0 COMMENT '客户数',
  active_customer_count INT NOT NULL DEFAULT 0 COMMENT '期间有销售客户数',
  avg_active_rate DECIMAL(18,6) NULL COMMENT '平均动销率',
  sale_qty DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期间销售量',
  purchase_qty DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期间购进量',
  end_stock_qty DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '期末库存量',
  stock_sale_ratio DECIMAL(18,6) NULL COMMENT '档位整体存销比=期末库存/期间销售',
  purchase_sale_ratio DECIMAL(18,6) NULL COMMENT '档位整体购销比=期间购进/期间销售',
  etl_loaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '报表生成时间',
  PRIMARY KEY (period_start_date, period_end_date, cust_seg_name),
  KEY idx_rpt_seg_ratio (period_end_date, stock_sale_ratio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='档位期间动销分析表';
